spring:
  application:
    name: back
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #sql을 보여줄때 보기 쉽게 표시해줌
        highlight_sql: true #색을 입혀서 보기 편하게 해줌
        use_sql_comments: true #jpa가 설명도 붙여줌